languageCode: en-us
baseURL: "http://adrian-maulana.com/"
title: Adrian Maulana Muhammad
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Adrian Maulana Muhammad
  description: "I am a Mathematics graduate from Institut Teknologi Sepuluh Nopember (ITS) Surabaya in Indonesia 🇮🇩 and a passionate full-stack data scientist who transforms raw data into impactful insights, and I thoroughly enjoy analyzing business cases. Feel free to reach out to me via the social media platforms listed below."
  keywords: [Adrian Maulana Muhammad, Portfolio, Data Engineer, Data Scientist, Data Analytics]
  #author: Adrian Maulana M.
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  math: True

  assets:
    disableHLJS: true 
    favicon: "/assets/favicon.ico"
    disableFingerprinting: true

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Adrian Maulana M."
    # icon: "images/home_img/icon.png"
    iconHeight: 70

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Hi, I'm Adrian \U0001F44B"
    subtitle: "A mathematics graduate from Institut Teknologi Sepuluh Nopember (ITS) in Indonesia 🇮🇩 and a passionate **data engineer** who transforms raw data into impactful insights. You can contact me via the social media platforms below:"
    imageUrl: "images/home_img/dp.jpeg"
    imageWidth: 220
    imageHeight: 220
    imageTitle: "Adrian Maulana Muhammad"
    buttons:
      - name: 📄 CV
        url: "https://tinyurl.com/CV-Adrian-Maulana-Muhammad"
        newTab: true
      - name: 📊 Portfolio
        url: 
        newTab: false

  # home-info mode
  homeInfoParams:
    Title: "Hi, I'm Adrian"
    Content: "I am a Mathematics graduate from the Institut Teknologi Sepuluh Nopember (ITS) Surabaya in Indonesia 🇮🇩 and a passionate full-stack data scientist who transforms raw data into impactful insights, and I thoroughly enjoy analyzing business cases. Feel free to reach out to me via the social media platforms listed below."

  socialIcons:
    - name: email
      url: "mailto:adrian.m.muhammad@gmail.com"
    - name: linkedin
      url: "https://www.linkedin.com/in/adrn-mm/"
    - name: github
      url: "https://github.com/adrn-mm"
    - name: medium
      url: "https://medium.com/@adrn-mm"
    - name: kaggle
      url: "https://www.kaggle.com/adrianmaulana"
    - name: hackerrank
      url: "https://www.hackerrank.com/adriantoto7"
    - name: youtube
      url: "https://www.youtube.com/@adrian-maulana"
    - name: twitter
      url: "https://twitter.com/adrn_mm"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: true # hide on single page
    linkFullImages: false # link full images


  editPost:
#    URL: "https://github.com/chanin-www/content"
#    Text: "Suggest Changes" # edit text
    URL: ""
    Text: "" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: blogs
      name: Blogs
      url: /blogs/
      weight: 2
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 3
    - identifier: visualizations
      name: Visualizations
      url: /visualizations/
      weight: 4
    - identifier: careers
      name: Careers
      url: /careers/
      weight: 5
    - identifier: tags
      name: Tags
      url: tags/
      weight: 6  
    - identifier: search
      name: Search
      url: /search/
      weight: 7

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

markup:
  defaultMarkdownHandler: "goldmark"
  goldmark:
    renderer:
      unsafe: true # Enable user to embed HTML snippets in Markdown content.

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
